Refactor code structure for improved readability and maintainability

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -21,16 +21,16 @@ jobs:
           node-version: 22.15.0
           cache: 'yarn'
 
-      # - name: Verify dependency integrity
-      #   run: |
-      #     set -o pipefail
+      - name: Verify dependency integrity
+        run: |
+          set -o pipefail
 
-      #     yarn install --frozen-lockfile --check-files 2>&1 | tee output.log
+          yarn install --frozen-lockfile --check-files 2>&1 | tee output.log
 
-      #     if grep -Ei 'error' output.log; then
-      #       echo "❌ Dependency issues (errors) found. Failing..."
-      #       exit 1
-      #     fi
+          if grep -Ei 'error' output.log; then
+            echo "❌ Dependency issues (errors) found. Failing..."
+            exit 1
+          fi
 
       - name: Run build
         run: yarn build
